import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { PageShell } from '@/components/layout';
import { Card } from '@/components/ui/Card';
import { LineChart, BarChart, DonutChart } from '@/components/charts';
import { MapView } from '@/components/map/MapView';
import { api } from '@/api/endpoints';
import { Site, SiteMetric } from '@/types';

export function SiteDetail() {
  const { id = '' } = useParams(); const [site, setSite] = useState<Site | null>(null); const [metrics, setMetrics] = useState<SiteMetric[]>([]); const [range, setRange] = useState('all');
  useEffect(() => { if (!id) return; api.sites.getSite(id).then(setSite); }, [id]);
  useEffect(() => { if (!id) return; const start = range === 'year' ? new Date(new Date().setFullYear(new Date().getFullYear() - 1)).toISOString().slice(0, 10) : undefined; api.metrics.getSiteMetrics(id, start).then(setMetrics); }, [id, range]);
  const latest = metrics.at(-1); const labels = metrics.map((metric) => new Date(metric.recorded_date).toLocaleDateString(undefined, { month: 'short', year: '2-digit' })); const line = { labels, datasets: [{ label: 'Canopy cover %', data: metrics.map((metric) => metric.canopy_cover_pct), borderColor: '#1B4332', yAxisID: 'cover' }, { label: 'NDVI', data: metrics.map((metric) => metric.ndvi), borderColor: '#89C2D9', yAxisID: 'ndvi' }] }; const carbon = { labels, datasets: [{ label: 'Carbon tCO₂e', data: metrics.map((metric) => metric.carbon_tco2e), backgroundColor: '#52796F' }] }; const health = Math.round(((latest?.canopy_cover_pct ?? 0) + (latest?.ndvi ?? 0) * 100 + (latest?.biodiversity_index ?? 0) * 100) / 3);
  if (!site) return <PageShell><p>Loading site…</p></PageShell>;
  return <PageShell><div className="mb-6 flex items-center justify-between"><div><h1 className="text-3xl">{site.name}</h1><p className="text-sm text-charcoal/60">{site.ecosystem_type}</p></div><select value={range} onChange={(event) => setRange(event.target.value)} className="rounded border p-2"><option value="all">All time</option><option value="year">Last year</option></select></div><div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><Card><p className="text-sm">Total area</p><b>{site.area_hectares.toFixed(1)} ha</b></Card><Card><p className="text-sm">Latest carbon</p><b>{latest?.carbon_tco2e?.toFixed(1) ?? '—'} tCO₂e</b></Card><Card><p className="text-sm">Biodiversity</p><b>{latest?.biodiversity_index?.toFixed(2) ?? '—'}</b></Card><Card><p className="text-sm">Last monitored</p><b>{latest?.recorded_date ?? '—'}</b></Card></div><div className="mb-6 grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><h2 className="mb-4 text-lg">Canopy and NDVI</h2><div className="h-64"><LineChart data={line} options={{ responsive: true, maintainAspectRatio: false, scales: { cover: { position: 'left' }, ndvi: { position: 'right', min: 0, max: 1, grid: { drawOnChartArea: false } } } }} /></div></Card><Card><h2 className="mb-4 text-lg">Site boundary</h2><MapView className="h-64" geojson={{ type: 'Feature', geometry: site.geojson, properties: {} }} /></Card></div><div className="grid gap-6 md:grid-cols-2"><Card><h2 className="mb-4 text-lg">Carbon trend</h2><div className="h-64"><BarChart data={carbon} options={{ maintainAspectRatio: false }} /></div></Card><Card><h2 className="mb-4 text-lg">Health score: {health}/100</h2><div className="h-64"><DonutChart data={{ labels: ['Health', 'Remaining'], datasets: [{ data: [health, 100 - health], backgroundColor: ['#52796F', '#e2e8f0'] }] }} options={{ maintainAspectRatio: false, cutout: '70%' }} /></div></Card></div></PageShell>;
}
